name: Release New Version

on:
  push:
    branches: [ master ]

jobs:
  pipeline:
    name: Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Create new GitHub tag
          id: new_tag
          uses: butlerlogic/action-autotag@stable
          with:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
            strategy: regex
            root: "version"
            regex_pattern: "^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$"
            tag_prefix: "v"
      - name: Create GitHub release
          if: github.ref == 'refs/heads/master'
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ steps.new_tag.outputs.tagname }}
            release_name: Release ${{ steps.new_tag.outputs.tagname }}
            draft: false
